/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package visual;

import entidades.Empleado;
import entidades.ErrorDatos;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import logica.GestorComercio;
import javax.swing.JOptionPane;

/**
 *
 * @author macky
 */
public class DlgEmpleado extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgEmpleado.class.getName());
    private GestorComercio gestor;
    private Empleado empleadoEdicion; // Si es null estamos creando; si tiene datos, editando

    /**
     * Constructor del Diálogo
     *
     * @param parent Ventana que lo invoca (FrmEmpleado)
     * @param modal Bloquea la ventana de atrás mientras está abierto
     */
    public DlgEmpleado(java.awt.Frame parent, boolean modal, GestorComercio gestor, Empleado empleado) {
        super(parent, modal);
        initComponents();

        this.gestor = gestor;
        this.empleadoEdicion = empleado;

        // Si nos pasaron un empleado, rellenamos los campos para EDITAR
        if (empleadoEdicion != null) {
            setTitle("Editar Empleado - Mazcu.fit");
            txtDNI.setText(empleadoEdicion.getDni());
            txtNombre.setText(empleadoEdicion.getNombre());
            txtApellidos.setText(empleadoEdicion.getApellidos());
            txtPuesto.setText(empleadoEdicion.getPuesto());
            this.txtCP.setText(empleadoEdicion.getCp());
            this.txtCategoria.setText(empleadoEdicion.getCategoria() + "");
            this.txtCiudad.setText(empleadoEdicion.getCiudad());
            this.txtTelefono.setText(empleadoEdicion.getTelefono());
            this.txtDireccion.setText(empleadoEdicion.getCalle());
            this.txtEmail.setText(empleadoEdicion.getEmail());
            this.txtFAntiguedadant.setText(empleadoEdicion.getAntiguedadAnterior() + "");
            DateTimeFormatter formato = DateTimeFormatter.ofPattern("d/M/yyyy");
            this.txtFContrato.setText(empleadoEdicion.getFechaContrato().format(formato));
            this.txtGrupo.setText(empleadoEdicion.getGrupo() + "");
            this.txtINSS.setText(empleadoEdicion.getNss());
            this.txtNivel.setText(empleadoEdicion.getNivel() + "");
            this.txtNumero.setText(empleadoEdicion.getNumero());
            this.txtProvincia.setText(empleadoEdicion.getProvincia());

            txtDNI.setEditable(false); // Normalmente el DNI/ID no se deja editar por seguridad
        } else {
            setTitle("Nuevo Empleado - Mazcu.fit");
        }

        this.setLocationRelativeTo(parent);
    }

    // Genera el evento clic del botón Cancelar (doble clic en btnCancelar)
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lblDNI = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        lblINSS = new javax.swing.JLabel();
        txtINSS = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblDirección = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblCiudad = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        lblProvinncia = new javax.swing.JLabel();
        txtProvincia = new javax.swing.JTextField();
        lblPuesto = new javax.swing.JLabel();
        txtPuesto = new javax.swing.JTextField();
        lblCategoria = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        lblGrupo = new javax.swing.JLabel();
        txtGrupo = new javax.swing.JTextField();
        lblNivel = new javax.swing.JLabel();
        txtNivel = new javax.swing.JTextField();
        lblFContrato = new javax.swing.JLabel();
        txtFContrato = new javax.swing.JTextField();
        lblAntiguedadAnt = new javax.swing.JLabel();
        txtFAntiguedadant = new javax.swing.JTextField();
        lblCP = new javax.swing.JLabel();
        txtCP = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnHoras1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nombre");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lblTitulo.setText("Empleado");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        lblNombre.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre.setText("Nombre");
        lblNombre.setToolTipText("");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 43, 60, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 40, 406, -1));

        lblApellidos.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        lblApellidos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblApellidos.setText("Apellidos");
        lblApellidos.setToolTipText("");
        getContentPane().add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 71, 60, -1));
        getContentPane().add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 68, 406, -1));

        lblDNI.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        lblDNI.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDNI.setText("DNI");
        lblDNI.setToolTipText("");
        getContentPane().add(lblDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 99, 31, -1));
        getContentPane().add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 96, 406, -1));

        lblINSS.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        lblINSS.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblINSS.setText("INSS");
        lblINSS.setToolTipText("");
        getContentPane().add(lblINSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 127, -1, -1));
        getContentPane().add(txtINSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 124, 406, -1));

        lblTelefono.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        lblTelefono.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTelefono.setText("Teléfono");
        lblTelefono.setToolTipText("");
        getContentPane().add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 155, 60, -1));

        txtTelefono.addActionListener(this::txtTelefonoActionPerformed);
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 152, 406, -1));

        lblEmail.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmail.setText("email");
        lblEmail.setToolTipText("");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 183, -1, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 180, 406, -1));

        lblDirección.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        lblDirección.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDirección.setText("Dirección");
        lblDirección.setToolTipText("");
        getContentPane().add(lblDirección, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 211, -1, -1));
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 208, 406, -1));

        lblNumero.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        lblNumero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumero.setText("Número");
        lblNumero.setToolTipText("");
        getContentPane().add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 239, -1, -1));
        getContentPane().add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 236, 406, -1));

        lblCiudad.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        lblCiudad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCiudad.setText("Ciudad");
        lblCiudad.setToolTipText("");
        getContentPane().add(lblCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 267, 50, -1));
        getContentPane().add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 264, 150, -1));

        lblProvinncia.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        lblProvinncia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProvinncia.setText("Provincia");
        lblProvinncia.setToolTipText("");
        getContentPane().add(lblProvinncia, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 295, -1, -1));
        getContentPane().add(txtProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 292, 406, -1));

        lblPuesto.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        lblPuesto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPuesto.setText("Puesto");
        lblPuesto.setToolTipText("");
        getContentPane().add(lblPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 323, -1, -1));
        getContentPane().add(txtPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 320, 406, -1));

        lblCategoria.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        lblCategoria.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCategoria.setText("Categoría (1-5)");
        lblCategoria.setToolTipText("");
        getContentPane().add(lblCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        txtCategoria.setColumns(2);
        getContentPane().add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 348, -1, -1));

        lblGrupo.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        lblGrupo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGrupo.setText("Grupo (1-5)");
        lblGrupo.setToolTipText("");
        getContentPane().add(lblGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

        txtGrupo.setColumns(2);
        getContentPane().add(txtGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, -1, -1));

        lblNivel.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        lblNivel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNivel.setText("Nivel (1-5)");
        lblNivel.setToolTipText("");
        getContentPane().add(lblNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, -1, -1));

        txtNivel.setColumns(2);
        getContentPane().add(txtNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 348, -1, -1));

        lblFContrato.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        lblFContrato.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFContrato.setText("Fecha Contrato");
        lblFContrato.setToolTipText("");
        getContentPane().add(lblFContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 379, 105, -1));

        txtFContrato.setText("dd/MM/yyyy");
        getContentPane().add(txtFContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 376, 170, -1));

        lblAntiguedadAnt.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        lblAntiguedadAnt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAntiguedadAnt.setText("Antiguedad Anterior");
        lblAntiguedadAnt.setToolTipText("");
        getContentPane().add(lblAntiguedadAnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 379, 141, -1));

        txtFAntiguedadant.setText("0.00");
        txtFAntiguedadant.addActionListener(this::txtFAntiguedadantActionPerformed);
        getContentPane().add(txtFAntiguedadant, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 376, -1, -1));

        lblCP.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        lblCP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCP.setText("Codigo Postal");
        lblCP.setToolTipText("");
        getContentPane().add(lblCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 267, 116, -1));
        getContentPane().add(txtCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 264, 100, -1));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(this::btnVolverActionPerformed);
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 416, 105, -1));

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(this::btnBorrarActionPerformed);
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 416, 105, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 416, 105, -1));

        btnHoras1.setText("Añadir Horas");
        btnHoras1.addActionListener(this::btnHoras1ActionPerformed);
        getContentPane().add(btnHoras1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 416, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        try {
            DateTimeFormatter formateador = DateTimeFormatter.ofPattern("d/M/yyyy");
            String dni = txtDNI.getText().trim();
            String nombre = txtNombre.getText().trim();
            String puesto = txtPuesto.getText().trim();
            String apellidos = txtApellidos.getText().trim();
            int categoria = Integer.parseInt(txtCategoria.getText().trim());
            String ciudad = txtCiudad.getText().trim();
            String direccion = txtDireccion.getText().trim();
            String email = txtEmail.getText().trim();
            LocalDate fechaContrato = LocalDate.parse(txtFContrato.getText().trim(), formateador);
            int grupo = Integer.parseInt(txtGrupo.getText().trim());
            String inss = txtINSS.getText().trim();
            int nivel = Integer.parseInt(txtNivel.getText().trim());
            String numero = txtNumero.getText().trim();
            String provincia = txtProvincia.getText().trim();
            String telefono = txtTelefono.getText().trim();
            String antiant = this.txtFAntiguedadant.getText().trim();
            double antiguedadAnt;
            if (antiant.matches("\\d{1,2}(\\.\\d{1,2})?")) {
                antiguedadAnt = Double.parseDouble(antiant);
            } else {
                antiguedadAnt = 0.00;
            }
            String cp = this.txtCP.getText().trim();

            if (dni.isEmpty() || nombre.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El DNI y el Nombre son obligatorios.");
                return;
            }

            if (empleadoEdicion == null) {

                gestor.crearEmpleado(nombre, apellidos, telefono, email,
                        dni, inss, direccion, numero, ciudad,
                        provincia, cp, categoria, grupo, nivel,
                        fechaContrato, puesto);
                JOptionPane.showMessageDialog(this, "Empleado creado con éxito.");
            } else {
                // --- MODO: EDITAR EMPLEADO ---
                empleadoEdicion.setNombre(nombre);
                empleadoEdicion.setPuesto(puesto);
                empleadoEdicion.setAntiguedadAnterior(antiguedadAnt);
                empleadoEdicion.setApellidos(apellidos);
                empleadoEdicion.setCalle(direccion);
                empleadoEdicion.setCategoria(categoria);
                empleadoEdicion.setCiudad(ciudad);
                empleadoEdicion.setCp(cp);
                empleadoEdicion.setDni(dni);
                empleadoEdicion.setEmail(email);
                empleadoEdicion.setFechaContrato(fechaContrato);
                empleadoEdicion.setGrupo(grupo);
                empleadoEdicion.setNivel(nivel);
                empleadoEdicion.setNumero(numero);
                empleadoEdicion.setProvincia(provincia);
                empleadoEdicion.setPuesto(puesto);
                empleadoEdicion.setTelefono(telefono);
                // Asumo que tienes un método similar a modificarEmpleado en tu gestor
                gestor.modificarEmpleado(empleadoEdicion);
                JOptionPane.showMessageDialog(this, "Empleado modificado con éxito.");
            }
        } catch (SQLException sqle) {
            JOptionPane.showMessageDialog(this, sqle.getMessage());

        } catch (ErrorDatos ed) {
            JOptionPane.showMessageDialog(this, ed.getMessage());
        }

        this.dispose(); // Cerramos el diálogo al terminar
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        try {
            gestor.borrarEmpleado(empleadoEdicion);
            this.dispose();
        } catch (ErrorDatos ed) {
            JOptionPane.showMessageDialog(this, ed.getMessage());
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnHoras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoras1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHoras1ActionPerformed

    private void txtFAntiguedadantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFAntiguedadantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFAntiguedadantActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnHoras1;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblAntiguedadAnt;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCP;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblDirección;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFContrato;
    private javax.swing.JLabel lblGrupo;
    private javax.swing.JLabel lblINSS;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblProvinncia;
    private javax.swing.JLabel lblPuesto;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCP;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFAntiguedadant;
    private javax.swing.JTextField txtFContrato;
    private javax.swing.JTextField txtGrupo;
    private javax.swing.JTextField txtINSS;
    private javax.swing.JTextField txtNivel;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtProvincia;
    private javax.swing.JTextField txtPuesto;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
