/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package visual;

import entidades.Empleado;
import java.time.YearMonth;
import java.time.format.TextStyle;
import java.util.Locale;
import javax.swing.JOptionPane;
import logica.GestorComercio;

/**
 *
 * @author macky
 */
public class DlgSeleccionarMesNomina extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgSeleccionarMesNomina.class.getName());

    private GestorComercio gestor;
    private Empleado empleado;
    private YearMonth[] mesesOpciones = new YearMonth[3];
    
    
    /**
     * Creates new form DlgSeleccionarMesNomina
     */
public DlgSeleccionarMesNomina(java.awt.Frame parent, boolean modal, GestorComercio gestor, Empleado empleado) {
        super(parent, modal);
        initComponents();
        
        this.gestor = gestor;
        this.empleado = empleado;
        
        setTitle("Nómina para: " + empleado.getNombre());
        calcularMesesAnteriores();
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbMeses = new javax.swing.JComboBox<>();
        txtHoras = new javax.swing.JTextField();
        btnSiguiente = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbMeses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtHoras.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtHoras.setText("0");

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(this::btnSiguienteActionPerformed);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        jLabel1.setText("(max 80 por año)");

        jLabel2.setText("Horas Extras Aplicables");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(10, 10, 10)
                        .addComponent(txtHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSiguiente)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(cbMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addComponent(txtHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiguiente)
                    .addComponent(btnCancelar))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        String textoHoras = txtHoras.getText().trim();

        // Validamos que hayan introducido las horas
        if (textoHoras.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, introduce las horas trabajadas en el mes.", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int horas = Integer.parseInt(textoHoras);
            if (horas < 0 || horas > 80) {
                JOptionPane.showMessageDialog(this, "Rango de horas Incorrecto.");
                return;
            }

            // Averiguamos cuál de los 3 meses seleccionó el usuario
            int indiceSeleccionado = cbMeses.getSelectedIndex();
            YearMonth mesNomina = mesesOpciones[indiceSeleccionado];

            // --- PASO CLAVE: ABRIR EL JFRAME DE LA NÓMINA ---
            // Creamos la ventana de impresión pasándole toda la información recogida
            FrmNomina ventanaNomina = new FrmNomina(gestor, empleado, mesNomina, horas);
            ventanaNomina.setVisible(true);

            this.dispose(); // Cerramos este cuadro de diálogo de selección

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Las horas deben ser un número entero válido.", "Error de formato", JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void calcularMesesAnteriores() {
        cbMeses.removeAllItems(); // Limpiamos el combo por seguridad
        YearMonth mesActual = YearMonth.now(); // Captura el mes y año de hoy

        for (int i = 0; i < 3; i++) {
            // Restamos i+1 meses (1 mes atrás, 2 meses atrás, 3 meses atrás)
            YearMonth mesAnterior = mesActual.minusMonths(i + 1);
            mesesOpciones[i] = mesAnterior; // Guardamos el objeto YearMonth para usarlo al guardar

            // Extraemos el nombre del mes en español con la primera letra en mayúscula
            String nombreMes = mesAnterior.getMonth().getDisplayName(TextStyle.FULL, new Locale("es", "ES"));
            nombreMes = nombreMes.substring(0, 1).toUpperCase() + nombreMes.substring(1);
            int anio = mesAnterior.getYear();

            // Añadimos el texto bonito al JComboBox (Ej: "Mayo de 2026")
            cbMeses.addItem(nombreMes + " de " + anio);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox<String> cbMeses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtHoras;
    // End of variables declaration//GEN-END:variables
}
