/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;

import entidades.Articulo;
import entidades.ProductoFisico;
import entidades.Servicio;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import logica.GestorComercio;

/**
 *
 * @author macky
 */
public class FrmArticulo extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmArticulo.class.getName());
    private static GestorComercio gestor;

    /**
     * Creates new form FrmArticulo
     */
    public FrmArticulo(GestorComercio gestor) {
        this.gestor = gestor;
        initComponents();
        configurarTabla();
        DefaultTableCellRenderer renderizadorFilas = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {

                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                String tipo = table.getValueAt(row, 1).toString();
                String infoExtra = table.getValueAt(row, 6).toString();

                if (tipo.equals("Servicio") && infoExtra.contains("min")) {

                    c.setBackground(new Color(255, 230, 230));
                    c.setForeground(Color.RED);
                } else {

                    c.setBackground(isSelected ? table.getSelectionBackground() : Color.WHITE);
                    c.setForeground(isSelected ? table.getSelectionForeground() : Color.BLACK);
                }

                return c;
            }
        };
        actualizarTabla(""); 
        txtPatron.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPatron = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblArticulo = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnNewArticulo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 400));

        jLabel1.setText("Articulo");

        jLabel2.setText("Buscarf");

        txtPatron.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPatronKeyReleased(evt);
            }
        });

        tblArticulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblArticulo);

        jPanel1.setLayout(new java.awt.GridLayout());

        btnBack.setText("Volver Atras");
        btnBack.addActionListener(this::btnBackActionPerformed);
        jPanel1.add(btnBack);

        btnNewArticulo.setText("Nuevo Articulo");
        jPanel1.add(btnNewArticulo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPatron))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPatron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        FrmMenuPrincipal menu = new FrmMenuPrincipal(this.gestor);
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtPatronKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPatronKeyReleased
        actualizarTabla(txtPatron.getText().trim());
    }//GEN-LAST:event_txtPatronKeyReleased

    private void actualizarTabla(String patron) {
        String[] columnas = {"ID", "Tipo", "Nombre", "Precio Base", "IVA", "P. Final", "Stock/Min"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);

        for (Articulo a : gestor.buscarArticulos(patron)) {
            Object[] fila = new Object[7];
            fila[0] = a.getId();
            fila[1] = (a instanceof ProductoFisico) ? "Producto" : "Servicio"; // Tipo
            fila[2] = a.getNombre();
            fila[3] = a.getPrecioBase();
            fila[4] = a.getIva() + "%";

            double pFinal = a.getPrecioBase() * (1 + (a.getIva() / 100.0));
            fila[5] = String.format("%.2f €", pFinal);

            if (a instanceof ProductoFisico) {
                fila[6] = ((ProductoFisico) a).getStock() + " uds";
            } else if (a instanceof Servicio) {
                Servicio s = (Servicio) a;
                String urgenteStr = s.isUrgente() ? " URGENTE" : "";
                fila[6] = s.getMinutos() + " min" + urgenteStr;
            }
            modelo.addRow(fila);
        }

        tblArticulo.setModel(modelo);

        DefaultTableCellRenderer renderizadorFilas = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {

                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                Object valorUrgencia = table.getValueAt(row, 6);
                boolean esUrgente = valorUrgencia != null && valorUrgencia.toString().contains("URGENTE");

                if (esUrgente) {
                    c.setBackground(new Color(255, 200, 200));
                    c.setForeground(Color.RED);
                    c.setFont(c.getFont().deriveFont(Font.BOLD));
                } else {
                    c.setBackground(isSelected ? table.getSelectionBackground() : Color.WHITE);
                    c.setForeground(isSelected ? table.getSelectionForeground() : Color.BLACK);
                    c.setFont(c.getFont().deriveFont(Font.PLAIN));
                }
                return c;
            }
        };

        for (int i = 0; i < tblArticulo.getColumnCount(); i++) {
            tblArticulo.getColumnModel().getColumn(i).setCellRenderer(renderizadorFilas);
        }

        tblArticulo.getColumnModel().getColumn(2).setPreferredWidth(350);
        tblArticulo.getColumnModel().getColumn(0).setPreferredWidth(50);
        //tblArticulo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
    }

    private void configurarTabla() {

        javax.swing.table.TableColumnModel columnModel = tblArticulo.getColumnModel();

        columnModel.getColumn(1).setPreferredWidth(350);
        columnModel.getColumn(0).setPreferredWidth(50);
        columnModel.getColumn(2).setPreferredWidth(80);
        columnModel.getColumn(6).setPreferredWidth(100);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmArticulo(gestor).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNewArticulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblArticulo;
    private javax.swing.JTextField txtPatron;
    // End of variables declaration//GEN-END:variables
}
