/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;

import entidades.AlertaStock;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import logica.GestorComercio;

/**
 *
 * @author macky
 */
public class FrmAlertasStock extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmAlertasStock.class.getName());

    private GestorComercio gestor;
    private List<AlertaStock> listaAlertas;

    public FrmAlertasStock(GestorComercio gestor) {
        this.gestor = gestor;

        initComponents();

        this.listaAlertas = gestor.getAlertaStock();
        llenarTabla();
        configurarEventos();

        setTitle("Panel de Alertas de Stock - Mazcu.fit");
        setLocationRelativeTo(null);
    }

    /**
     * Creates new form FrmAlertasStock
     */
    public FrmAlertasStock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAlertas = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaAlertas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Stock", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaAlertas);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVolver)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        new FrmMenuPrincipal(gestor).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void llenarTabla() {
        // 1. Obtenemos el modelo de la tabla para poder manipular las filas
        DefaultTableModel modeloTabla = (DefaultTableModel) tablaAlertas.getModel();

        // 2. Limpiamos la tabla por si tuviera filas viejas o de ejemplo
        modeloTabla.setRowCount(0);

        // 3. Recorremos la lista de alertas que nos dio el gestor
        for (AlertaStock alerta : listaAlertas) {
            Object[] fila = {
                alerta.getId(),
                alerta.getNombreArticulo(),
                alerta.getStockActual(),
                alerta.getFechaAlerta()
            };

            modeloTabla.addRow(fila);
        }
    }

    private void configurarEventos() {
        tablaAlertas.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                // Evaluamos si el usuario hizo DOBLE CLIC
                if (e.getClickCount() == 2) {
                    int filaSeleccionada = tablaAlertas.getSelectedRow();

                    // Nos aseguramos de que realmente haya una fila seleccionada
                    if (filaSeleccionada != -1) {
                        // 1. Obtenemos la AlertaStock correspondiente a esa fila
                        AlertaStock alertaSeleccionada = listaAlertas.get(filaSeleccionada);

                        // 2. Extraemos el Artículo de la alerta
                        entidades.Articulo articuloAEditar = gestor.selecionarArticulo(alertaSeleccionada.getId());

                        // 3. Abrimos FrmArticulo pasándole el gestor
                        FrmArticulo ventanaEdicion = new FrmArticulo(gestor);

                        // 4. Le pasamos el artículo para que rellene los campos automáticamente
                        ventanaEdicion.cargarArticuloParaEditar(articuloAEditar);

                        // 5. Mostramos la edición y cerramos las alertas
                        ventanaEdicion.setVisible(true);
                        dispose();
                    }
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAlertas;
    // End of variables declaration//GEN-END:variables
}
