/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;

import entidades.Articulo;
import entidades.ProductoFisico;
import entidades.Servicio;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import logica.GestorComercio;

/**
 *
 * @author macky
 */
public class FrmArticulo extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmArticulo.class.getName());
    private static GestorComercio gestor;
    //private boolean productosSi, serviciosSi;

    /**
     * Creates new form FrmArticulo
     */
    public FrmArticulo(GestorComercio gestor) {
        this.gestor = gestor;
        initComponents();

        productosSi.setSelected(true);
        serviciosSi.setSelected(true);
        productosSi.addActionListener(e -> actualizarTabla(txtPatron.getText().trim()));
        serviciosSi.addActionListener(e -> actualizarTabla(txtPatron.getText().trim()));

        actualizarTabla("");
        configurarTabla();
        txtPatron.requestFocus();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPatron = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblArticulo = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnNewArticulo = new javax.swing.JButton();
        productosSi = new javax.swing.JCheckBox();
        serviciosSi = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 400));

        jLabel1.setText("Articulos");

        jLabel2.setText("Buscarf");

        txtPatron.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPatronKeyReleased(evt);
            }
        });

        tblArticulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Tipo", "Nombre", "Precio", "IVA", "PrecioIVA", "Stock/Minutos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblArticulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblArticuloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblArticulo);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        btnBack.setText("Volver Atras");
        btnBack.addActionListener(this::btnBackActionPerformed);
        jPanel1.add(btnBack);

        btnNewArticulo.setText("Nuevo Articulo");
        btnNewArticulo.addActionListener(this::btnNewArticuloActionPerformed);
        jPanel1.add(btnNewArticulo);

        productosSi.setText("Productos");
        productosSi.addActionListener(this::productosSiActionPerformed);

        serviciosSi.setText("Servicios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPatron)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(productosSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serviciosSi)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPatron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productosSi)
                    .addComponent(serviciosSi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        FrmMenuPrincipal menu = new FrmMenuPrincipal(this.gestor);
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtPatronKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPatronKeyReleased
        actualizarTabla(txtPatron.getText().trim());
    }//GEN-LAST:event_txtPatronKeyReleased

    private void btnNewArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewArticuloActionPerformed
        FrmNuevoArticulo dialogo = new FrmNuevoArticulo(this, true, gestor, "PRODUCTO");
        dialogo.setLocationRelativeTo(this);
        dialogo.setVisible(true);
        actualizarTabla("");
    }//GEN-LAST:event_btnNewArticuloActionPerformed

    private void productosSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productosSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productosSiActionPerformed

    private void tblArticuloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblArticuloMouseClicked
        // Revisamos que sea doble clic y que realmente haya una fila seleccionada
        if (evt.getClickCount() == 2 && tblArticulo.getSelectedRow() != -1) {

            // Si la tabla intentó activar la edición de texto por defecto, la cancelamos
            if (tblArticulo.isEditing()) {
                tblArticulo.getCellEditor().cancelCellEditing();
            }

            int filaSeleccionada = tblArticulo.getSelectedRow();

            // 1. Tomamos el ID de la columna 0 (asegúrate de que en tu tabla el ID sea la primera columna)
            int idArticulo = (int) tblArticulo.getValueAt(filaSeleccionada, 0);

            // 2. Buscamos el artículo en el gestor por su ID
            Articulo articuloAEditar = gestor.selecionarArticulo(idArticulo);

            if (articuloAEditar != null) {
                // 3. Abrimos el JDialog pasando el objeto que apunta a la memoria
                FrmNuevoArticulo dialogo = new FrmNuevoArticulo(this, true, gestor, articuloAEditar);
                dialogo.setVisible(true);

                // 4. Al cerrar el diálogo, refrescamos la tabla con los datos que ya cambiaron en memoria
                actualizarTabla(txtPatron.getText().trim());
            }
        }

    }//GEN-LAST:event_tblArticuloMouseClicked

    private void actualizarTabla(String patron) {
        String[] columnas = {"ID", "Tipo", "Nombre", "Precio Base", "IVA", "P. Final", "Stock/Min"};

        DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        boolean mostrarFisicos = productosSi.isSelected();
        boolean mostrarServicios = serviciosSi.isSelected();

        for (Articulo a : gestor.buscarArticulos(patron)) {

            // Switch de expresión con Pattern Matching de Java 24
            Object[] fila = switch (a) {
                case ProductoFisico p when mostrarFisicos -> {
                    Object[] f = crearFilaBase(p, "Producto");
                    f[6] = p.getStock() + " uds";
                    yield f;
                }
                case Servicio s when mostrarServicios -> {
                    Object[] f = crearFilaBase(s, "Servicio");
                    String urgenteStr = s.isUrgente() ? " URGENTE" : "";
                    f[6] = s.getMinutos() + " min" + urgenteStr; // Corregido a s.getMinutos()
                    yield f;
                }
                default ->
                    null;
            };

            if (fila != null) {
                modelo.addRow(fila);
            }
        }

        tblArticulo.setModel(modelo);

        // Renderizador para pintar las celdas de servicios urgentes
        DefaultTableCellRenderer renderizadorFilas = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {

                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                Object valorUrgencia = table.getValueAt(row, 6);
                boolean esUrgente = valorUrgencia != null && valorUrgencia.toString().contains("URGENTE");

                if (esUrgente) {
                    c.setBackground(new Color(255, 200, 200));
                    c.setForeground(Color.RED);
                    c.setFont(c.getFont().deriveFont(Font.BOLD));
                } else {
                    c.setBackground(isSelected ? table.getSelectionBackground() : Color.WHITE);
                    c.setForeground(isSelected ? table.getSelectionForeground() : Color.BLACK);
                    c.setFont(c.getFont().deriveFont(Font.PLAIN));
                }
                return c;
            }
        };

        for (int i = 0; i < tblArticulo.getColumnCount(); i++) {
            tblArticulo.getColumnModel().getColumn(i).setCellRenderer(renderizadorFilas);
        }

        tblArticulo.getColumnModel().getColumn(2).setPreferredWidth(350);
        tblArticulo.getColumnModel().getColumn(0).setPreferredWidth(50);
    }

    private void configurarTabla() {
        javax.swing.table.TableColumnModel columnModel = tblArticulo.getColumnModel();
        columnModel.getColumn(1).setPreferredWidth(350);
        columnModel.getColumn(0).setPreferredWidth(50);
        columnModel.getColumn(2).setPreferredWidth(80);
        columnModel.getColumn(6).setPreferredWidth(100);
    }

    private Object[] crearFilaBase(Articulo a, String tipo) {
        Object[] fila = new Object[7];
        fila[0] = a.getId();
        fila[1] = tipo;
        fila[2] = a.getNombre();
        fila[3] = a.getPrecioBase();
        fila[4] = a.getIva() + "%";

        double pFinal = a.getPrecioBase() * (1 + (a.getIva() / 100.0));
        fila[5] = String.format("%.2f €", pFinal);
        return fila;
    }

    public void cargarArticuloParaEditar(entidades.Articulo articulo) {
        if (articulo != null) {
            // 1. Ponemos el nombre del artículo en tu buscador txtPatron
            txtPatron.setText(articulo.getNombre());

            // 2. Ejecutamos tu método de actualizar para que la tabla solo muestre este artículo
            actualizarTabla(articulo.getNombre().trim());

            // 3. Opcional: Seleccionamos la primera fila (que será nuestro artículo filtrado)
            if (tblArticulo.getRowCount() > 0) {
                tblArticulo.setRowSelectionInterval(0, 0);
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNewArticulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox productosSi;
    private javax.swing.JCheckBox serviciosSi;
    private javax.swing.JTable tblArticulo;
    private javax.swing.JTextField txtPatron;
    // End of variables declaration//GEN-END:variables
}
