/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;

import entidades.Cliente;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.GestorComercio;
import static proyecto2526.Main.gestor;

/**
 *
 * @author macky
 */
public class FrmCliente extends javax.swing.JFrame {

    private static GestorComercio gestor;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCliente.class.getName());

    /**
     * Creates new form FrmCliente
     */
    public FrmCliente(GestorComercio gestor) {
        this.gestor = gestor;
        initComponents();
        tblCliente.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblCliente.getColumnModel().getColumn(0).setPreferredWidth(50);
        //tblCliente.getColumnModel().getColumn(0).setMaxWidth(100);
        tblCliente.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblCliente.setFillsViewportHeight(true);

        actualizarTabla("");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPatron = new javax.swing.JTextField();
        scpCliente = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnVolverAtras = new javax.swing.JButton();
        btnNuevoCliente = new javax.swing.JButton();
        btnDesignado = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 300));

        jLabel1.setText("Clientes");

        jLabel2.setText("Buscar");

        txtPatron.addActionListener(this::txtPatronActionPerformed);
        txtPatron.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPatronKeyReleased(evt);
            }
        });

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scpCliente.setViewportView(tblCliente);

        jPanel1.setLayout(new java.awt.GridLayout());

        btnVolverAtras.setText("Volver Atras");
        btnVolverAtras.addActionListener(this::btnVolverAtrasActionPerformed);
        jPanel1.add(btnVolverAtras);

        btnNuevoCliente.setText("Nuevo Cliente");
        btnNuevoCliente.addActionListener(this::btnNuevoClienteActionPerformed);
        jPanel1.add(btnNuevoCliente);

        btnDesignado.setText("Cliente Designado");
        btnDesignado.addActionListener(this::btnDesignadoActionPerformed);
        jPanel1.add(btnDesignado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPatron))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scpCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPatron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPatronKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPatronKeyReleased
        String patron = txtPatron.getText();
        List<Cliente> result = gestor.buscarClientes(patron);

// 3. ¡CAMBIO CLAVE! Usamos DefaultTableModel en lugar de ListModel
        String[] titulos = {"ID", "Nombre", "Apellidos", "Teléfono", "Email"};
        DefaultTableModel modeloTabla = new DefaultTableModel(titulos, 0);

        // 4. Llenamos el modelo de la tabla fila por fila
        for (Cliente c : result) {
            Object[] fila = {
                c.getId(),
                c.getNombre(),
                c.getApellidos(),
                c.getTelefono(),
                c.getEmail()
            };
            modeloTabla.addRow(fila);
        }

        // 5. Se lo asignamos a la tabla (asegúrate de que el nombre sea tblClientes)
        tblCliente.setModel(modeloTabla);

    }//GEN-LAST:event_txtPatronKeyReleased

    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClienteActionPerformed
        FrmNuevoCliente frmNuevo = new FrmNuevoCliente(this, true, gestor);
        frmNuevo.setVisible(true);
        actualizarTabla("");
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    private void txtPatronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatronActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatronActionPerformed

    private void btnDesignadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesignadoActionPerformed
        int fila = tblCliente.getSelectedRow();

        if (fila != -1) {
            // 1. Sacamos el ID de la tabla (Columna 0)
            int idCliente = (int) tblCliente.getValueAt(fila, 0);

            // 2. Obtenemos la lista actual (usando el patrón que hay en el buscador)
            String patron = txtPatron.getText();
            List<Cliente> listaActual = gestor.buscarClientes(patron);

            // 3. Usamos TU método optimizado
            Cliente seleccionado = gestor.selecionarCliente(listaActual, idCliente);

            // 4. Lo guardamos en el gestor
            if (seleccionado != null) {
                gestor.setClienteActual(seleccionado);
                JOptionPane.showMessageDialog(this, "Cliente designado: " + seleccionado.getNombre());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona un cliente de la tabla.");
        }
    }//GEN-LAST:event_btnDesignadoActionPerformed

    private void btnVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverAtrasActionPerformed
        this.dispose();
        FrmMenuPrincipal menu = new FrmMenuPrincipal(gestor);
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
    }//GEN-LAST:event_btnVolverAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmCliente(gestor).setVisible(true));
    }

    private void actualizarTabla(String patron) {
        // Definimos las columnas
        String[] titulos = {"ID", "Nombre", "Apellidos", "Teléfono", "Email", "Fid."};
        DefaultTableModel modelo = new DefaultTableModel(titulos, 0);

        // Pedimos los objetos al gestor
        List<Cliente> lista = gestor.buscarClientes(patron);

        // Pasamos los objetos a filas de la tabla
        for (Cliente c : lista) {
            Object[] fila = {
                c.getId(),
                c.getNombre(),
                c.getApellidos(),
                c.getTelefono(),
                c.getEmail(),
                c.getNivelFidelidad()
            };
            modelo.addRow(fila);
        }
        tblCliente.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesignado;
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JButton btnVolverAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane scpCliente;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTextField txtPatron;
    // End of variables declaration//GEN-END:variables
}
