/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;

import java.util.List;
import javax.swing.table.DefaultTableModel;

import logica.GestorComercio;
import entidades.Empleado;

/**
 *
 * @author macky
 */
  

    public class FrmEmpleado extends javax.swing.JFrame {

        private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmEmpleado.class.getName());

        private GestorComercio gestor;
        private DefaultTableModel modeloTabla;

        /**
         * Creates new form FrmEmpleado
         */
        public FrmEmpleado(GestorComercio gestor) {
            this.gestor = gestor;

            // 1. Inicializa lo que arrastraste en el diseño visual
            initComponents();

            // 2. Vinculamos el modelo de la tabla que creaste en el diseño
            this.modeloTabla = (DefaultTableModel) tblEmpleado.getModel();

            // 3. Ejecutamos la carga inicial (trae todos los empleados al abrir)
            actualizarTabla("");

            // Estética inicial
            this.setLocationRelativeTo(null);
            txtPatron.requestFocus();
        }

        /**
         * Lee la base de datos a través del gestor empleando la confluencia
         * escrita
         */
        private void actualizarTabla(String patron) {
            // Limpiamos las filas que tenga la tabla visual actualmente
            modeloTabla.setRowCount(0);

            // Invocamos a tu método del gestor pasándole la confluencia
            List<Empleado> listaEmpleados = gestor.buscarEmpleados(patron);

            // Recorremos y añadimos cada empleado al diseño visual
            for (Empleado emp : listaEmpleados) {
                // Ajusta estos métodos (.getId(), .getDni(), etc.) a los nombres reales en tu entidad Empleado
                Object[] fila = {
                    emp.getId(),
                    emp.getDni(),
                    emp.getNombreCompleto(),
                    emp.getPuesto(),
                    emp.getDni(),
                    emp.getNss(),
                    emp.getTelefono(),
                    emp.getEmail()
                };
                modeloTabla.addRow(fila);
            }
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        txtPatron = new javax.swing.JTextField();
        btnNuevoEmpleado = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleado = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("FreeSans", 1, 24)); // NOI18N
        lblTitulo.setText("Empleados");

        txtPatron.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPatronKeyReleased(evt);
            }
        });

        btnNuevoEmpleado.setText("Nuevo Empleado");

        btnVolver.setText("Volver al Menú");
        btnVolver.addActionListener(this::btnVolverActionPerformed);

        tblEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellidos", "Puesto", "DNI", "INSS", "Teléfono", "email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEmpleado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNuevoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPatron, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitulo))
                        .addGap(0, 373, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPatron, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoEmpleado)
                    .addComponent(btnVolver))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPatronKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPatronKeyReleased
        actualizarTabla(txtPatron.getText().trim());
    }//GEN-LAST:event_txtPatronKeyReleased

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        new FrmMenuPrincipal(gestor).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevoEmpleado;
    private javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblEmpleado;
    private javax.swing.JTextField txtPatron;
    // End of variables declaration//GEN-END:variables
}
