package visual;

import java.awt.Color;
import javax.swing.JOptionPane;
import logica.GestorComercio;
import static proyecto2526.Main.gestor;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author macky
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName());
    private static GestorComercio gestor;

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal(GestorComercio gestor) {
        this.gestor = gestor;
        initComponents();
        
        actualizarColorBotonEstado();
        btnEstado.addActionListener(e -> mostrarInformacionEstado());
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGeneral = new javax.swing.JPanel();
        btnClientes = new javax.swing.JButton();
        btnArticulos = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();
        btnPersonal = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        if (Logo.getIcon() != null) {
            java.awt.Image img = ((javax.swing.ImageIcon)Logo.getIcon()).getImage();
            java.awt.Image newImg = img.getScaledInstance(Logo.getWidth(), Logo.getHeight(), java.awt.Image.SCALE_SMOOTH);
            Logo.setIcon(new javax.swing.ImageIcon(newImg));
        }
        btnEstado = new javax.swing.JToggleButton();
        Título = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(50, 50, 50));

        btnClientes.setText("Clientes");
        btnClientes.addActionListener(this::btnClientesActionPerformed);

        btnArticulos.setText("Articulos");
        btnArticulos.addActionListener(this::btnArticulosActionPerformed);

        btnPedidos.setText("Pedidos");
        btnPedidos.addActionListener(this::btnPedidosActionPerformed);

        btnPersonal.setText("Personal");

        javax.swing.GroupLayout jPanelGeneralLayout = new javax.swing.GroupLayout(jPanelGeneral);
        jPanelGeneral.setLayout(jPanelGeneralLayout);
        jPanelGeneralLayout.setHorizontalGroup(
            jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelGeneralLayout.setVerticalGroup(
            jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Logo.setIcon(new javax.swing.ImageIcon("/Users/29160712r/NetBeansProjects/UD08/ProyectoP/logo.png")); // NOI18N

        btnEstado.setText("Estado del Stock");

        Título.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        Título.setText("Mazcu.fit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Título, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Título)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                    .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        FrmCliente vCliente = new FrmCliente(gestor);
        vCliente.setLocationRelativeTo(null);
        vCliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArticulosActionPerformed
        FrmArticulo ventanaArticulos = new FrmArticulo(gestor);
        ventanaArticulos.setLocationRelativeTo(null);
        ventanaArticulos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnArticulosActionPerformed

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed
        if (gestor.getClienteActual() == null) {
            JOptionPane.showMessageDialog(this,
                    "Para gestionar pedidos, primero debes seleccionar un Cliente en la sección de Clientes.",
                    "Cliente no seleccionado",
                    JOptionPane.WARNING_MESSAGE);
            FrmCliente ventanaClientes = new FrmCliente(gestor);
            ventanaClientes.setVisible(true);
            this.dispose();
        } else {
            FrmPedido ventanaPedidos = new FrmPedido(gestor);
            ventanaPedidos.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnPedidosActionPerformed


    private void actualizarColorBotonEstado() {
        btnEstado.setFocusPainted(false); // Elimina el recuadro de enfoque estético
        
        // Importante en JToggleButton para evitar que cambie drásticamente al hacer clic
        btnEstado.setContentAreaFilled(true); 
        btnEstado.setOpaque(true);

        if (gestor.estadoRojo()) {
            btnEstado.setBackground(Color.RED);
            btnEstado.setForeground(Color.WHITE);
        } else if (gestor.estadoAmbar()) {
            btnEstado.setBackground(Color.ORANGE);
            btnEstado.setForeground(Color.BLACK);
        } else if (gestor.estadoVerde()) {
            btnEstado.setBackground(Color.GREEN);
            btnEstado.setForeground(Color.BLACK);
        } else {
            btnEstado.setBackground(Color.GRAY);
            btnEstado.setForeground(Color.WHITE);
        }
    }
    
    private void mostrarInformacionEstado() {
        String mensaje;

        if (gestor.estadoRojo()) {
            mensaje = "Estado ROJO: El stock está críticamente bajo. Requiere reposición inmediata.";
        } else if (gestor.estadoAmbar()) {
            mensaje = "Estado ÁMBAR: Algunos artículos están llegando al límite mínimo establecido.";
        } else if (gestor.estadoVerde()) {
            mensaje = "Estado VERDE: Los niveles de stock son óptimos.";
        } else {
            mensaje = "No se ha podido determinar el estado actual del inventario.";
        }

        JOptionPane.showMessageDialog(
                this, 
                mensaje, 
                "Estado del Stock - Mazcu.fit", 
                JOptionPane.INFORMATION_MESSAGE
        );
        
        // Opcional: Como es un JToggleButton, tras hacer clic y cerrar el cuadro de diálogo
        // solemos querer que el botón no se quede "hundido". Esto lo deselecciona:
        btnEstado.setSelected(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Título;
    private javax.swing.JButton btnArticulos;
    private javax.swing.JButton btnClientes;
    private javax.swing.JToggleButton btnEstado;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnPersonal;
    private javax.swing.JPanel jPanelGeneral;
    // End of variables declaration//GEN-END:variables
}
