package visual;

import javax.swing.JOptionPane;
import logica.GestorComercio;
import static proyecto2526.Main.gestor;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author macky
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName());
    private static GestorComercio gestor;

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal(GestorComercio gestor) {
        this.gestor = gestor;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelGeneral = new javax.swing.JPanel();
        btnClientes = new javax.swing.JButton();
        btnArticulos = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelGeneral.setLayout(new java.awt.GridLayout(1, 0));

        btnClientes.setText("Clientes");
        btnClientes.addActionListener(this::btnClientesActionPerformed);
        jPanelGeneral.add(btnClientes);

        btnArticulos.setText("Articulos");
        btnArticulos.addActionListener(this::btnArticulosActionPerformed);
        jPanelGeneral.add(btnArticulos);

        btnPedidos.setText("Pedidos");
        btnPedidos.addActionListener(this::btnPedidosActionPerformed);
        jPanelGeneral.add(btnPedidos);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 97;
        gridBagConstraints.ipady = 241;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        getContentPane().add(jPanelGeneral, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        FrmCliente vCliente = new FrmCliente(gestor);
        vCliente.setLocationRelativeTo(null);
        vCliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArticulosActionPerformed
        FrmArticulo ventanaArticulos = new FrmArticulo(gestor);
        ventanaArticulos.setLocationRelativeTo(null);
        ventanaArticulos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnArticulosActionPerformed

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed
        if (gestor.getClienteActual() == null) {
            JOptionPane.showMessageDialog(this,
                "Para gestionar pedidos, primero debes seleccionar un Cliente en la sección de Clientes.",
                "Cliente no seleccionado",
                JOptionPane.WARNING_MESSAGE);
            FrmCliente ventanaClientes = new FrmCliente(gestor);
            ventanaClientes.setVisible(true);
            this.dispose();
        } else {
            FrmPedido ventanaPedidos = new FrmPedido(gestor);
            ventanaPedidos.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnPedidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMenuPrincipal(gestor).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArticulos;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JPanel jPanelGeneral;
    // End of variables declaration//GEN-END:variables
}
