/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package visual;

import entidades.Articulo;
import entidades.Cliente;
import entidades.ErrorDatos;
import entidades.LineaPedido;
import entidades.Pedido;
import entidades.ProductoFisico;
import javax.swing.JOptionPane;
import logica.GestorComercio;

/**
 *
 * @author macky
 */
  

    public class FrmNuevoPedido extends javax.swing.JDialog {

        private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmNuevoPedido.class.getName());
        private GestorComercio gestor;
        private Pedido pedidoEnCurso;
        private java.util.List<Articulo> articulosMostrados; // Para sincronizar la tabla con la lista
        private Articulo articuloSeleccionado = null; // El que está listo para añadir

        /**
         * Creates new form FrmNuevoPedido
         */
        public FrmNuevoPedido(java.awt.Frame parent, boolean modal, GestorComercio gestor) throws ErrorDatos {
            super(parent, modal);
            this.gestor = gestor;
            initComponents();
            Cliente cliente = gestor.getClienteActual();
            gestor.iniciarPedido(cliente);
            pedidoEnCurso = gestor.obtenerPedidoEnCurso();
            lblCliente.setText("Cliente: " + cliente.getNombre() + " " + cliente.getApellidos());
            cargarTablaArticulos("");
            String[] cabecera = {"Cant.", "Artículo", "IVA", "P. Unit.", "Total Línea"};
            javax.swing.table.DefaultTableModel modeloInicial = new javax.swing.table.DefaultTableModel(cabecera, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            tblLineasDerecha.setModel(modeloInicial);

            this.setLocationRelativeTo(parent);

        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCliente = new javax.swing.JLabel();
        txtNombreArticulo = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblArticulos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLineasDerecha = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnConfimarLineaPedido = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnConfirmarPedidoEnCurso = new javax.swing.JButton();
        btnBorrarPedidoEnCurso = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCliente.setText(" ");

        txtNombreArticulo.addActionListener(this::txtNombreArticuloActionPerformed);
        txtNombreArticulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreArticuloKeyReleased(evt);
            }
        });

        txtCantidad.addActionListener(this::txtCantidadActionPerformed);

        tblArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Stock", "Nombre", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblArticulosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblArticulos);

        tblLineasDerecha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblLineasDerecha);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        btnConfimarLineaPedido.setText("Confimar Linea de Pedido");
        btnConfimarLineaPedido.addActionListener(this::btnConfimarLineaPedidoActionPerformed);

        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTotal.setText("Total Pedido: ");

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        btnConfirmarPedidoEnCurso.setText("Confirmar Pedido");
        btnConfirmarPedidoEnCurso.addActionListener(this::btnConfirmarPedidoEnCursoActionPerformed);
        jPanel2.add(btnConfirmarPedidoEnCurso);

        btnBorrarPedidoEnCurso.setText("Cancelar");
        btnBorrarPedidoEnCurso.addActionListener(this::btnBorrarPedidoEnCursoActionPerformed);
        jPanel2.add(btnBorrarPedidoEnCurso);

        jLabel2.setText("Cantidad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNombreArticulo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(btnConfimarLineaPedido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))))
                    .addComponent(lblCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConfimarLineaPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotal)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarPedidoEnCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarPedidoEnCursoActionPerformed
        gestor.cancelarPedido();
        this.dispose();
    }//GEN-LAST:event_btnBorrarPedidoEnCursoActionPerformed

    private void btnConfirmarPedidoEnCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarPedidoEnCursoActionPerformed
        if (pedidoEnCurso.getLista().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No puedes guardar un pedido vacío.");
            return;
        }
        try {
            gestor.confirmarPedido();
        } catch (ErrorDatos ex) {
            System.getLogger(FrmNuevoPedido.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        JOptionPane.showMessageDialog(this, "¡Pedido guardado con éxito!");
        this.dispose();
    }//GEN-LAST:event_btnConfirmarPedidoEnCursoActionPerformed

    private void tblArticulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblArticulosMouseClicked
        int fila = tblArticulos.getSelectedRow();
        if (fila != -1) {
            articuloSeleccionado = articulosMostrados.get(fila);
            txtNombreArticulo.setText(articuloSeleccionado.getNombre());
            txtCantidad.setText("1");
            txtCantidad.requestFocus();
        }
    }//GEN-LAST:event_tblArticulosMouseClicked

    private void btnConfimarLineaPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfimarLineaPedidoActionPerformed
        if (articuloSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona un artículo de la tabla primero.");
            return;
        }

        try {
            int cantidad = Integer.parseInt(txtCantidad.getText());
            if (cantidad <= 0) {
                throw new NumberFormatException();
            }
            gestor.anadirLineaPedido(articuloSeleccionado, cantidad);
            articuloSeleccionado = null;
            txtNombreArticulo.setText("");
            txtCantidad.setText("");
            actualizarTablaLineasDerecha();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La cantidad debe ser un número entero mayor que 0.");
        } catch (ErrorDatos ex) {
            System.getLogger(FrmNuevoPedido.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnConfimarLineaPedidoActionPerformed

    private void txtNombreArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreArticuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreArticuloActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtNombreArticuloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreArticuloKeyReleased
        cargarTablaArticulos(txtNombreArticulo.getText().trim());
    }//GEN-LAST:event_txtNombreArticuloKeyReleased

        private void cargarTablaArticulos(String filtro) {
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblArticulos.getModel();
            modelo.setRowCount(0);

            articulosMostrados = gestor.buscarArticulos(filtro);

            for (Articulo art : articulosMostrados) {
                String infoStock = "-";
                if (art instanceof ProductoFisico) {
                    ProductoFisico producto = (ProductoFisico) art;
                    infoStock = String.valueOf(producto.getStock());
                }
                modelo.addRow(new Object[]{infoStock, art.getNombre(), art.precioUnitario() + " €"});
            }
        }

        private void actualizarTablaLineasDerecha() throws ErrorDatos {
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblLineasDerecha.getModel();
            modelo.setRowCount(0); // Borramos todo antes de pintar para no duplicar filas visuales

            for (LineaPedido linea : pedidoEnCurso.getLista()) {
                int cant = linea.getCantidad();
                String nombre = linea.getArticulo().getNombre();
                double ivaPorcentaje = linea.getArticulo().getIva();
                double pUnitario = linea.getPrecioUnitarioFinal();
                double totalFila = pUnitario * cant;

                modelo.addRow(new Object[]{
                    cant,
                    nombre,
                    ivaPorcentaje + "%",
                    String.format("%.2f €", pUnitario),
                    String.format("%.2f €", totalFila)
                });
            }

            lblTotal.setText(String.format("Total Pedido: %.2f €", pedidoEnCurso.calcularTotal()));

        }

   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarPedidoEnCurso;
    private javax.swing.JButton btnConfimarLineaPedido;
    private javax.swing.JButton btnConfirmarPedidoEnCurso;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblArticulos;
    private javax.swing.JTable tblLineasDerecha;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtNombreArticulo;
    // End of variables declaration//GEN-END:variables
}
