/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;

import Nominas.Complementos;
import Nominas.Tabla;

import entidades.Empleado;
import java.time.LocalDate;
import java.time.Month;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.time.format.TextStyle;
import java.util.Locale;
import logica.GestorComercio;

/**
 *
 * @author macky
 */
public class FrmNomina extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmNomina.class.getName());

    /**
     * Creates new form FrmNomina
     */
    public FrmNomina(GestorComercio gestor, Empleado emp, YearMonth mesNomina, int horas) {
        initComponents();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("d/M/yyyy");
        lbFechaContrato.setText(emp.getFechaContrato().format(formato));
        lbINSS.setText(emp.getNss());
        lbNombre.setText(emp.getNombreCompleto());
        lbPuesto.setText(emp.getPuesto());
        ldDirección.setText(emp.getCiudad());
        this.lbCPCiudadProvincia.setText(
                emp.getCp() + "  "
                + emp.getCiudad() + "  "
                + emp.getProvincia());
        this.lbNIF.setText(emp.getDni());
        String nombreMes = mesNomina.getMonth().getDisplayName(
                java.time.format.TextStyle.FULL,
                new java.util.Locale("es", "ES")
        );
        nombreMes = nombreMes.substring(0, 1).toUpperCase() + nombreMes.substring(1);
        this.lbMes.setText(nombreMes + " de " + mesNomina.getYear());
        lblDiasMes.setText(mesNomina.lengthOfMonth() + "");
        
        calculoNomina (emp, mesNomina, horas);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ldEmpresaNonbre = new javax.swing.JLabel();
        lbDirEmp = new javax.swing.JLabel();
        lbCPEmp = new javax.swing.JLabel();
        ldCIFEMP = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ldTitulo1a = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        ldDirección = new javax.swing.JLabel();
        lbCPCiudadProvincia = new javax.swing.JLabel();
        ldCIFEMP1 = new javax.swing.JLabel();
        lbINSS = new javax.swing.JLabel();
        lbNIF = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbPuesto = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbFechaContrato = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel32 = new javax.swing.JLabel();
        lblDiasMes = new javax.swing.JLabel();
        lbMes = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ldT2 = new javax.swing.JLabel();
        ldT3 = new javax.swing.JLabel();
        ldT4 = new javax.swing.JLabel();
        ldT5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txSueldoBase = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txCDestino = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txCEspecifico = new javax.swing.JTextField();
        txTotalHoras = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txCantHoras = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txCComPorcent = new javax.swing.JTextField();
        txCComunes = new javax.swing.JTextField();
        txCProfesionales = new javax.swing.JTextField();
        txCProfessPorcent = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txRetenciones = new javax.swing.JTextField();
        txRetPorcent = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txTotalSueldoParcial = new javax.swing.JTextField();
        txTotalReten = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txTotalSueldoParcial2 = new javax.swing.JTextField();
        txRetPorcent2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txTotalCobrar = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txTotalSueldoParcial3 = new javax.swing.JTextField();
        txProRat = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txTotalBCCC = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txTipoTrabCC = new javax.swing.JTextField();
        txTotalBCCC2 = new javax.swing.JTextField();
        txtTipoEmpCC = new javax.swing.JTextField();
        txCComunes2 = new javax.swing.JTextField();
        txTotalEmpCC = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txTotalEmpCP = new javax.swing.JTextField();
        txtTipoEmpCP = new javax.swing.JTextField();
        txCProfesionales2 = new javax.swing.JTextField();
        txTipoTrabCP = new javax.swing.JTextField();
        txTotalBCCP = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txTotalTrabContingencias = new javax.swing.JTextField();
        txTotalEmpContingencias = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("DejaVu Sans", 1, 48)); // NOI18N
        lblTitulo.setText("Mazcu.Fit");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 17, 280, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 6, -1, -1));

        ldEmpresaNonbre.setText("Mazcu.Fit S.L.");
        jPanel1.add(ldEmpresaNonbre, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 104, -1, -1));

        lbDirEmp.setText("Carretera Ribarroja s/n");
        jPanel1.add(lbDirEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 126, -1, -1));

        lbCPEmp.setText("46940 Manises (Valencia)");
        jPanel1.add(lbCPEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 148, -1, -1));

        ldCIFEMP.setText("CIF: A12345678");
        jPanel1.add(ldCIFEMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 170, -1, -1));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel1.setText("Cuenta de cotización");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 192, -1, -1));

        jLabel4.setText("46/1234567/89");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 214, -1, -1));

        ldTitulo1a.setText("Recibo Nómina de ");
        jPanel1.add(ldTitulo1a, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        lbNombre.setText("Nombre Empleado");
        jPanel1.add(lbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 104, 243, -1));

        ldDirección.setText("Dirección");
        jPanel1.add(ldDirección, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 126, 243, -1));

        lbCPCiudadProvincia.setText("CP - Ciudad (Provincia)");
        jPanel1.add(lbCPCiudadProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 148, 243, -1));

        ldCIFEMP1.setText("NIF:");
        jPanel1.add(ldCIFEMP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 170, -1, -1));

        lbINSS.setText("46/12345678/12");
        jPanel1.add(lbINSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 170, 107, -1));

        lbNIF.setText("12345678L");
        jPanel1.add(lbNIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 170, 74, -1));

        jLabel3.setText("INSS:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 170, -1, -1));

        jLabel5.setText("Puesto:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 192, -1, -1));

        lbPuesto.setText("Puesto");
        jPanel1.add(lbPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 192, 178, -1));

        jLabel6.setText("Antiguedad:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, -1));
        jPanel1.add(lbFechaContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 100, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 600, -1));

        jLabel32.setText("dias");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, 20));

        lblDiasMes.setText("dias");
        jPanel1.add(lblDiasMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 30, 20));

        lbMes.setText("Mes");
        jPanel1.add(lbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 140, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ldT2.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        ldT2.setText("Concepto");
        jPanel2.add(ldT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        ldT3.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        ldT3.setText("Cantidad");
        jPanel2.add(ldT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        ldT4.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        ldT4.setText("Precio");
        jPanel2.add(ldT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        ldT5.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        ldT5.setText("Devengos");
        jPanel2.add(ldT5, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 10, -1, -1));

        jLabel7.setText("Sueldo Base");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 32, -1, -1));

        txSueldoBase.setEditable(false);
        txSueldoBase.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txSueldoBase.setText("1000.00");
        txSueldoBase.setBorder(null);
        jPanel2.add(txSueldoBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 32, -1, -1));

        jLabel8.setText("Complemento de Destino");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 54, -1, -1));

        txCDestino.setEditable(false);
        txCDestino.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txCDestino.setText("1000.00");
        txCDestino.setBorder(null);
        jPanel2.add(txCDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 54, -1, -1));

        jLabel9.setText("Complemento Especifico");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 76, -1, -1));

        txCEspecifico.setEditable(false);
        txCEspecifico.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txCEspecifico.setText("1000.00");
        txCEspecifico.setBorder(null);
        jPanel2.add(txCEspecifico, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 76, -1, -1));

        txTotalHoras.setEditable(false);
        txTotalHoras.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txTotalHoras.setText("1000.00");
        txTotalHoras.setBorder(null);
        jPanel2.add(txTotalHoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 98, -1, -1));

        jLabel10.setText("Horas  Extras");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 98, -1, -1));

        txCantHoras.setEditable(false);
        txCantHoras.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txCantHoras.setText("0");
        txCantHoras.setBorder(null);
        txCantHoras.addActionListener(this::txCantHorasActionPerformed);
        jPanel2.add(txCantHoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 98, -1, -1));

        jLabel11.setText("Cuota Empleado C. Comunes");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        txCComPorcent.setEditable(false);
        txCComPorcent.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txCComPorcent.setText("4.85");
        txCComPorcent.setBorder(null);
        txCComPorcent.addActionListener(this::txCComPorcentActionPerformed);
        jPanel2.add(txCComPorcent, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 120, -1, -1));

        txCComunes.setEditable(false);
        txCComunes.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txCComunes.setText("100.00");
        txCComunes.setBorder(null);
        jPanel2.add(txCComunes, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 120, -1, -1));

        txCProfesionales.setEditable(false);
        txCProfesionales.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txCProfesionales.setText("50.00");
        txCProfesionales.setBorder(null);
        jPanel2.add(txCProfesionales, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 142, -1, -1));

        txCProfessPorcent.setEditable(false);
        txCProfessPorcent.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txCProfessPorcent.setText("1.65");
        txCProfessPorcent.setBorder(null);
        txCProfessPorcent.addActionListener(this::txCProfessPorcentActionPerformed);
        jPanel2.add(txCProfessPorcent, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 142, -1, -1));

        jLabel12.setText("Cuota Empleado C. Profesionales");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 142, -1, -1));

        jLabel13.setText("Retención a cuenta IRPF");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 164, -1, -1));

        txRetenciones.setEditable(false);
        txRetenciones.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txRetenciones.setText("1000.00");
        txRetenciones.setBorder(null);
        jPanel2.add(txRetenciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 164, -1, -1));

        txRetPorcent.setEditable(false);
        txRetPorcent.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txRetPorcent.setText("19.84");
        txRetPorcent.setBorder(null);
        txRetPorcent.addActionListener(this::txRetPorcentActionPerformed);
        jPanel2.add(txRetPorcent, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 164, -1, -1));

        jLabel14.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Total");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 186, -1, -1));

        txTotalSueldoParcial.setEditable(false);
        txTotalSueldoParcial.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txTotalSueldoParcial.setText("1000.00");
        txTotalSueldoParcial.setBorder(null);
        txTotalSueldoParcial.addActionListener(this::txTotalSueldoParcialActionPerformed);
        jPanel2.add(txTotalSueldoParcial, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 186, -1, -1));

        txTotalReten.setEditable(false);
        txTotalReten.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txTotalReten.setText("1000.00");
        txTotalReten.setBorder(null);
        jPanel2.add(txTotalReten, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 186, -1, -1));

        jLabel15.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Base IRPF");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 195, -1, -1));

        txTotalSueldoParcial2.setEditable(false);
        txTotalSueldoParcial2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txTotalSueldoParcial2.setText("1000");
        txTotalSueldoParcial2.setBorder(null);
        txTotalSueldoParcial2.addActionListener(this::txTotalSueldoParcial2ActionPerformed);
        jPanel2.add(txTotalSueldoParcial2, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 195, -1, -1));

        txRetPorcent2.setEditable(false);
        txRetPorcent2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txRetPorcent2.setText("19.84");
        txRetPorcent2.setBorder(null);
        txRetPorcent2.addActionListener(this::txRetPorcent2ActionPerformed);
        jPanel2.add(txRetPorcent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 217, -1, -1));

        jLabel16.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Retencion %");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 217, -1, -1));

        txTotalCobrar.setEditable(false);
        txTotalCobrar.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        txTotalCobrar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txTotalCobrar.setText("1000.00");
        txTotalCobrar.setBorder(null);
        txTotalCobrar.addActionListener(this::txTotalCobrarActionPerformed);
        jPanel2.add(txTotalCobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, -1, -1));

        jLabel17.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Cuota Líquida");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 600, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 600, 260));

        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setText("Remuneración Mensual");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 6, -1, -1));

        txTotalSueldoParcial3.setEditable(false);
        txTotalSueldoParcial3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txTotalSueldoParcial3.setText("1000.00");
        txTotalSueldoParcial3.setBorder(null);
        txTotalSueldoParcial3.addActionListener(this::txTotalSueldoParcial3ActionPerformed);
        jPanel3.add(txTotalSueldoParcial3, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 6, -1, -1));

        txProRat.setEditable(false);
        txProRat.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txProRat.setText("250.00");
        txProRat.setBorder(null);
        txProRat.addActionListener(this::txProRatActionPerformed);
        jPanel3.add(txProRat, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 28, -1, -1));

        jLabel19.setText("Prorratas Paga Extra");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 28, -1, -1));

        jLabel20.setText("Total Base Bruta");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 50, -1, -1));

        txTotalBCCC.setEditable(false);
        txTotalBCCC.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txTotalBCCC.setText("1250.00");
        txTotalBCCC.setBorder(null);
        txTotalBCCC.addActionListener(this::txTotalBCCCActionPerformed);
        jPanel3.add(txTotalBCCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 50, -1, -1));

        jLabel21.setText("Concepto");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 72, -1, -1));

        txTipoTrabCC.setEditable(false);
        txTipoTrabCC.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txTipoTrabCC.setText("4.85");
        txTipoTrabCC.setBorder(null);
        txTipoTrabCC.addActionListener(this::txTipoTrabCCActionPerformed);
        jPanel3.add(txTipoTrabCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 100, -1, -1));

        txTotalBCCC2.setEditable(false);
        txTotalBCCC2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txTotalBCCC2.setText("1250.00");
        txTotalBCCC2.setBorder(null);
        txTotalBCCC2.addActionListener(this::txTotalBCCC2ActionPerformed);
        jPanel3.add(txTotalBCCC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        txtTipoEmpCC.setEditable(false);
        txtTipoEmpCC.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTipoEmpCC.setText("24.35");
        txtTipoEmpCC.setBorder(null);
        txtTipoEmpCC.addActionListener(this::txtTipoEmpCCActionPerformed);
        jPanel3.add(txtTipoEmpCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        txCComunes2.setEditable(false);
        txCComunes2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txCComunes2.setText("100.00");
        txCComunes2.setBorder(null);
        txCComunes2.addActionListener(this::txCComunes2ActionPerformed);
        jPanel3.add(txCComunes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 100, -1, -1));

        txTotalEmpCC.setEditable(false);
        txTotalEmpCC.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txTotalEmpCC.setText("500.00");
        txTotalEmpCC.setBorder(null);
        txTotalEmpCC.addActionListener(this::txTotalEmpCCActionPerformed);
        jPanel3.add(txTotalEmpCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, -1, -1));

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Concepto");
        jLabel22.setToolTipText("");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 72, -1, -1));

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Concepto");
        jLabel23.setToolTipText("");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 72, -1, -1));

        jLabel24.setText("Bases");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        jLabel25.setText("Contingencias Comunes");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 100, -1, -1));

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("Concepto");
        jLabel26.setToolTipText("");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 72, -1, -1));

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("Concepto");
        jLabel27.setToolTipText("");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 72, -1, -1));

        jLabel28.setText("Empresa");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 50, -1, -1));

        jLabel29.setText("Trabajador");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 50, -1, -1));

        txTotalEmpCP.setEditable(false);
        txTotalEmpCP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txTotalEmpCP.setText("18.00");
        txTotalEmpCP.setBorder(null);
        txTotalEmpCP.addActionListener(this::txTotalEmpCPActionPerformed);
        jPanel3.add(txTotalEmpCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 128, -1, -1));

        txtTipoEmpCP.setEditable(false);
        txtTipoEmpCP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTipoEmpCP.setText("7.80");
        txtTipoEmpCP.setBorder(null);
        txtTipoEmpCP.addActionListener(this::txtTipoEmpCPActionPerformed);
        jPanel3.add(txtTipoEmpCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 128, -1, -1));

        txCProfesionales2.setEditable(false);
        txCProfesionales2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txCProfesionales2.setText("50.00");
        txCProfesionales2.setBorder(null);
        txCProfesionales2.addActionListener(this::txCProfesionales2ActionPerformed);
        jPanel3.add(txCProfesionales2, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 128, -1, -1));

        txTipoTrabCP.setEditable(false);
        txTipoTrabCP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txTipoTrabCP.setText("1.65");
        txTipoTrabCP.setBorder(null);
        txTipoTrabCP.addActionListener(this::txTipoTrabCPActionPerformed);
        jPanel3.add(txTipoTrabCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 128, -1, -1));

        txTotalBCCP.setEditable(false);
        txTotalBCCP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txTotalBCCP.setText("1250.00");
        txTotalBCCP.setBorder(null);
        txTotalBCCP.addActionListener(this::txTotalBCCPActionPerformed);
        jPanel3.add(txTotalBCCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jLabel30.setText("Contingencias Profesionales");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 128, -1, -1));

        jLabel31.setText("Total");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 156, -1, -1));

        txTotalTrabContingencias.setEditable(false);
        txTotalTrabContingencias.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txTotalTrabContingencias.setText("150.00");
        txTotalTrabContingencias.setBorder(null);
        txTotalTrabContingencias.addActionListener(this::txTotalTrabContingenciasActionPerformed);
        jPanel3.add(txTotalTrabContingencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 156, -1, -1));

        txTotalEmpContingencias.setEditable(false);
        txTotalEmpContingencias.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txTotalEmpContingencias.setText("18.00");
        txTotalEmpContingencias.setBorder(null);
        txTotalEmpContingencias.addActionListener(this::txTotalEmpContingenciasActionPerformed);
        jPanel3.add(txTotalEmpContingencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 156, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 600, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txCantHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCantHorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txCantHorasActionPerformed

    private void txCComPorcentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCComPorcentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txCComPorcentActionPerformed

    private void txCProfessPorcentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCProfessPorcentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txCProfessPorcentActionPerformed

    private void txRetPorcentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txRetPorcentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txRetPorcentActionPerformed

    private void txTotalSueldoParcialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTotalSueldoParcialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTotalSueldoParcialActionPerformed

    private void txTotalSueldoParcial2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTotalSueldoParcial2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTotalSueldoParcial2ActionPerformed

    private void txRetPorcent2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txRetPorcent2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txRetPorcent2ActionPerformed

    private void txTotalCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTotalCobrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTotalCobrarActionPerformed

    private void txTotalSueldoParcial3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTotalSueldoParcial3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTotalSueldoParcial3ActionPerformed

    private void txProRatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txProRatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txProRatActionPerformed

    private void txTotalBCCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTotalBCCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTotalBCCCActionPerformed

    private void txTipoTrabCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTipoTrabCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTipoTrabCCActionPerformed

    private void txTotalBCCC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTotalBCCC2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTotalBCCC2ActionPerformed

    private void txtTipoEmpCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoEmpCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoEmpCCActionPerformed

    private void txCComunes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCComunes2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txCComunes2ActionPerformed

    private void txTotalEmpCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTotalEmpCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTotalEmpCCActionPerformed

    private void txTotalEmpCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTotalEmpCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTotalEmpCPActionPerformed

    private void txtTipoEmpCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoEmpCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoEmpCPActionPerformed

    private void txCProfesionales2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCProfesionales2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txCProfesionales2ActionPerformed

    private void txTipoTrabCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTipoTrabCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTipoTrabCPActionPerformed

    private void txTotalBCCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTotalBCCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTotalBCCPActionPerformed

    private void txTotalTrabContingenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTotalTrabContingenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTotalTrabContingenciasActionPerformed

    private void txTotalEmpContingenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTotalEmpContingenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTotalEmpContingenciasActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        this.dispose();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        this.dispose();
    }//GEN-LAST:event_jPanel3MouseClicked

    private void calculoNomina(Empleado emp, YearMonth mesNomina, int horasXtra) {

        Tabla tS25 = new Tabla();
        Complementos cpt = new Complementos();

        double sb = tS25.getBaseMes(emp.getGrupo(), emp.getNivel());
        this.txSueldoBase.setText(String.format("%6.2f", sb));
        double cd = cpt.getComplementoDestino();
        this.txCDestino.setText(String.format("%6.2f", cd));
        double ce = cpt.getComplementoEspecifico(emp.getCategoria());
        this.txCantHoras.setText(String.format("%8d", horasXtra));
        double hXt = cpt.getHoraXtra()*horasXtra;
        this.txTotalHoras.setText(String.format("%6.2f", hXt));
        double tSP = sb + cd + ce + hXt;
        this.txTotalSueldoParcial.setText(String.format("%6.2f", tSP));
        this.txTotalSueldoParcial2.setText(this.txTotalSueldoParcial.getText());
        this.txTotalSueldoParcial3.setText(this.txTotalSueldoParcial.getText());
        double irpf = tSP * 0.1984;
        this.txRetenciones.setText(String.format("%6.2f", irpf));
        double reten = irpf;
        this.txProRat.setText(String.format("%6.2f", sb/6));

        double prorat = (sb + cd)/6;
        this.txProRat.setText(String.format("%6.2f", prorat));
        double bccc = sb + prorat + cd + ce;
        this.txTotalBCCC.setText(String.format("%6.2f", bccc));
        this.txTotalBCCC2.setText(this.txTotalBCCC.getText());
        double bccp = bccc + cpt.getHoraXtra() * horasXtra;
        this.txTotalBCCP.setText(String.format("%6.2f", bccp));
        double qbccc = bccc * 0.0483;
        double qbccp = bccp * 0.0165;

        this.txCComunes.setText(String.format("%6.2f", qbccc));
        this.txCComunes2.setText(this.txCComunes.getText());
        this.txCProfesionales.setText(String.format("%6.2f", qbccp));
        this.txCProfesionales2.setText(this.txCProfesionales.getText());
        double tReten= irpf + qbccc + qbccp;
        this.txTotalReten.setText(String.format("%6.2f", tReten));
        double cecc = bccc * 0.2435;
        this.txTotalEmpCC.setText(String.format("%6.2f", cecc));
        double cecp = bccp * 0.078 ;
        this.txTotalEmpCP.setText(String.format("%6.2f", cecp));
        this.txTotalTrabContingencias.setText(String.format("%6.2f", qbccc + qbccp));
        this.txTotalEmpContingencias.setText(String.format("%6.2f", cecc + cecp));
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbCPCiudadProvincia;
    private javax.swing.JLabel lbCPEmp;
    private javax.swing.JLabel lbDirEmp;
    private javax.swing.JLabel lbFechaContrato;
    private javax.swing.JLabel lbINSS;
    private javax.swing.JLabel lbMes;
    private javax.swing.JLabel lbNIF;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbPuesto;
    private javax.swing.JLabel lblDiasMes;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel ldCIFEMP;
    private javax.swing.JLabel ldCIFEMP1;
    private javax.swing.JLabel ldDirección;
    private javax.swing.JLabel ldEmpresaNonbre;
    private javax.swing.JLabel ldT2;
    private javax.swing.JLabel ldT3;
    private javax.swing.JLabel ldT4;
    private javax.swing.JLabel ldT5;
    private javax.swing.JLabel ldTitulo1a;
    private javax.swing.JTextField txCComPorcent;
    private javax.swing.JTextField txCComunes;
    private javax.swing.JTextField txCComunes2;
    private javax.swing.JTextField txCDestino;
    private javax.swing.JTextField txCEspecifico;
    private javax.swing.JTextField txCProfesionales;
    private javax.swing.JTextField txCProfesionales2;
    private javax.swing.JTextField txCProfessPorcent;
    private javax.swing.JTextField txCantHoras;
    private javax.swing.JTextField txProRat;
    private javax.swing.JTextField txRetPorcent;
    private javax.swing.JTextField txRetPorcent2;
    private javax.swing.JTextField txRetenciones;
    private javax.swing.JTextField txSueldoBase;
    private javax.swing.JTextField txTipoTrabCC;
    private javax.swing.JTextField txTipoTrabCP;
    private javax.swing.JTextField txTotalBCCC;
    private javax.swing.JTextField txTotalBCCC2;
    private javax.swing.JTextField txTotalBCCP;
    private javax.swing.JTextField txTotalCobrar;
    private javax.swing.JTextField txTotalEmpCC;
    private javax.swing.JTextField txTotalEmpCP;
    private javax.swing.JTextField txTotalEmpContingencias;
    private javax.swing.JTextField txTotalHoras;
    private javax.swing.JTextField txTotalReten;
    private javax.swing.JTextField txTotalSueldoParcial;
    private javax.swing.JTextField txTotalSueldoParcial2;
    private javax.swing.JTextField txTotalSueldoParcial3;
    private javax.swing.JTextField txTotalTrabContingencias;
    private javax.swing.JTextField txtTipoEmpCC;
    private javax.swing.JTextField txtTipoEmpCP;
    // End of variables declaration//GEN-END:variables
}
