/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package visual;

import entidades.ErrorDatos;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import logica.GestorComercio;

/**
 *
 * @author macky
 */
public class FrmNuevoArticulo extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmNuevoArticulo.class.getName());
    private GestorComercio gestor;
    private String tipo;

    /**
     * Creates new form FrmNuevoArticulo
     */
    public FrmNuevoArticulo(java.awt.Frame parent, boolean modal, GestorComercio gestor, String tipo) {
        super(parent, modal);
        this.gestor = gestor;
        initComponents();
        this.tipo = tipo;
        getRootPane().registerKeyboardAction(e -> {
            this.dispose();
        }, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_IN_FOCUSED_WINDOW);
        if (tipo.equals("PRODUCTO")) {
            rbProducto.setSelected(true);
        } else {
            rbServicio.setSelected(true);
        }
        rbProducto.addActionListener(e -> actualizarCamposSegunTipo());
        rbServicio.addActionListener(e -> actualizarCamposSegunTipo());
        actualizarCamposSegunTipo();
        this.setLocationRelativeTo(parent);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTipo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnNuevoArticulo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbIVA = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        chkUrgente = new javax.swing.JCheckBox();
        lblStock = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblMinutos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rbProducto = new javax.swing.JRadioButton();
        rbServicio = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout());

        btnBack.setText("Volver Atras");
        btnBack.addActionListener(this::btnBackActionPerformed);
        jPanel1.add(btnBack);

        btnNuevoArticulo.setText("Crear Articulo");
        btnNuevoArticulo.addActionListener(this::btnNuevoArticuloActionPerformed);
        jPanel1.add(btnNuevoArticulo);

        jLabel1.setText("Nuevo Articulo");

        jLabel2.setText("Nombre");

        jLabel3.setText("Precio");

        jLabel4.setText("IVA aplicable");

        cmbIVA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "21% (General)", "10% (Reducido)", "4% (Superreducido)", "0% (Exento)" }));
        cmbIVA.addActionListener(this::cmbIVAActionPerformed);

        chkUrgente.setText("Servicio Urgente");

        jLabel5.setText("Stock");

        jLabel6.setText("Duración Estimada (minutos)");

        btnTipo.add(rbProducto);
        rbProducto.setText("Producto Físico");

        btnTipo.add(rbServicio);
        rbServicio.setText("Servicio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(chkUrgente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblMinutos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                    .addComponent(lblStock, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(rbProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbServicio)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbProducto)
                    .addComponent(rbServicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkUrgente)
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoArticuloActionPerformed
        try {
            // Campos comunes
            String nombre = txtNombre.getText();
            double precioBase = Double.parseDouble(txtPrecio.getText());
            double iva = obtenerIVA();

            if (rbProducto.isSelected()) {
                // Lógica Producto Físico
                int stock = Integer.parseInt(lblStock.getText());
                gestor.crearProductoFisico(nombre, precioBase, iva, stock);

            } else {
                // Lógica Servicio
                int minutos = Integer.parseInt(lblMinutos.getText());
                boolean urgente = chkUrgente.isSelected();
                gestor.crearServicio(nombre, precioBase, iva, minutos, urgente);
            }

            // Si llegamos aquí, todo ha ido bien
            this.dispose();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, revisa que el precio y los minutos sean números válidos.");
        } catch (SQLException ex) {
            System.getLogger(FrmNuevoArticulo.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (ErrorDatos ex) {
            System.getLogger(FrmNuevoArticulo.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnNuevoArticuloActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        if (!txtNombre.getText().isEmpty()) {
            int respuesta = JOptionPane.showConfirmDialog(this,
                    "¿Seguro que quieres salir? Se perderán los datos introducidos.",
                    "Confirmar salida",
                    JOptionPane.YES_NO_OPTION);

            if (respuesta == JOptionPane.YES_OPTION) {
                this.dispose();
            }
        } else {
            this.dispose();
        }

    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbIVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbIVAActionPerformed

    private double obtenerIVA() {
        String seleccion = (String) cmbIVA.getSelectedItem();

        // Usamos un switch o una serie de if para convertir el texto a número
        if (seleccion.contains("21")) {
            return 21.0;
        }
        if (seleccion.contains("10")) {
            return 10.0;
        }
        if (seleccion.contains("4")) {
            return 4.0;
        }

        return 0.0; // Por defecto 0%
    }

    private void actualizarCamposSegunTipo() {
        // Si el radio button de producto está marcado, esto será true
        boolean esProducto = rbProducto.isSelected();

        // --- CAMPOS DE PRODUCTO ---
        lblStock.setEnabled(esProducto);
        lblStock.setEnabled(esProducto);

        // --- CAMPOS DE SERVICIO ---
        lblMinutos.setEnabled(!esProducto);
        lblMinutos.setEnabled(!esProducto);
        chkUrgente.setEnabled(!esProducto);

        // Limpiamos datos para evitar errores ocultos
        if (!esProducto) {
            lblStock.setText("0");
        } else {
            lblMinutos.setText("0");
            chkUrgente.setSelected(false);
        }
    }

    private void rbProductoActionPerformed(java.awt.event.ActionEvent evt) {
        actualizarCamposSegunTipo();
    }

    private void rbServicioActionPerformed(java.awt.event.ActionEvent evt) {
        actualizarCamposSegunTipo();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNuevoArticulo;
    private javax.swing.ButtonGroup btnTipo;
    private javax.swing.JCheckBox chkUrgente;
    private javax.swing.JComboBox<String> cmbIVA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lblMinutos;
    private javax.swing.JTextField lblStock;
    private javax.swing.JRadioButton rbProducto;
    private javax.swing.JRadioButton rbServicio;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
